benzinga-exchange/portfolio/urls.py
from django.conf.urls import patterns, url

from portfolio import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<symbol>[\w-]+)/$', views.exchange, name='exchange'),
    url(r'^register', views.register, name='register'),
)

benzinga-exchange/zingexchange/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.views import login, logout
from django.contrib import admin

from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = patterns('',
    # Examples:
    url(r'^$', login),
    # url(r'^blog/', include('blog.urls')),

    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$',  login),
    url(
        r'^accounts/logout/$','django.contrib.auth.views.logout',
        dict(
            template_name = 'registration/logout.html',
        ),
        name='logout',
    ),

)

urlpatterns += staticfiles_urlpatterns()

benzinga-exchange/portfolio/models.py
from decimal import *

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    balance = models.DecimalField(default=100000.0, decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal('0.00'))], blank=False, null=False)

def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.\
                 objects.get_or_create(user=instance)
post_save.connect(create_profile, sender=User)

class Holdings(models.Model):
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False)
	symbol = models.CharField(max_length=64, blank=False, null=False )
	company_name = models.CharField(max_length=256, blank=False, null=False)
	quantity = models.IntegerField(default=0, blank=False, null=False, validators=[MinValueValidator(0)])
	price_paid = models.DecimalField(decimal_places=2, max_digits=12, validators=[MinValueValidator(Decimal('0.01'))], blank=False, null=False)

	class Meta:
		unique_together = (("owner", "symbol"),)

	def __str__(self):
		return str("%s %s %d" % (self.owner, self.symbol, self.quantity))

benzinga-exchange/portfolio/forms.py
from django import forms

class OrderForm(forms.Form):
    symbol = forms.CharField()
    quantity = forms.IntegerField(min_value=1)
    order_type = forms.CharField()

benzinga-exchange/portfolio/views.py
# Benzinga Exchange Code Challenge
# Written by Steve Rawlinson
# September 3, 2014

from django import forms
from django.shortcuts import render
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

from portfolio.models import Holdings
from portfolio.forms import OrderForm

import urllib2
import json
from decimal import *

# === User Management ===
def register(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			new_user = form.save()

			# new_user = authenticate(username=request.POST['username'],
            #                         password=request.POST.get('password', ''))
			# login(request, new_user)
			return HttpResponseRedirect("/portfolio/")
	else:
		form = UserCreationForm()
	return render(request, "registration/register.html", {
        'form': form,
    })


def logout_view_old(request):
    logout(request)
    return HttpResponseRedirect("/accounts/login")


def index(request):
	# get portfolio values after any orders placed
	if request.user.is_authenticated():
		# Do something for authenticated users.
		stock_list = None
		if request.user:
			stock_list = Holdings.objects.filter(owner=request.user)
		return render(request, 'portfolio/exchange.html', {'stock_list': stock_list})
	
	return HttpResponseRedirect("/portfolio/register")


# === Helper Functions ===
def get_symbol(symbol):
	# lookup that symbol with Benzinga API
	response = urllib2.urlopen('http://data.benzinga.com/stock/' + symbol)
	data = json.load(response)
	
	if data.has_key('status') and data['status'] == 'error':
		return None
		
	return data


@login_required
def place_order(request, symbol, order_type, quantity):
	user = request.user.userprofile	
    	
	try:
		data = get_symbol(symbol)
	except:
		# Redisplay the question voting form.
		return (False, "Unknown symbol")
	else:
		bid_price = Decimal(data['bid'])
		ask_price = Decimal(data['ask'])

		if order_type == 'buy':
			# check balance
			if user.balance >= (quantity * ask_price):
				# check if user already owns stock
				try:
					stock= Holdings.objects.get(owner=request.user, symbol=symbol)
					stock.quantity = stock.quantity + quantity
					stock.price_paid = ask_price  # *** TODO *** This is incorrect, should it be a weighted average?
					stock.save()
				except Holdings.DoesNotExist:
					stock = Holdings(owner=request.user, symbol=symbol, company_name=data['name'], quantity=quantity, price_paid = ask_price)
					stock.save()

				user.balance = user.balance - (quantity * ask_price)				
				user.save()
			else:
				return (False, "Insufficent funds.")
        
		elif order_type == 'sell':
			# check quantity to sell
			try:
				user_stock = Holdings.objects.get(owner=request.user, symbol=symbol)
			except:
				return (False, "You do not own any of that stock to sell.")
			if (user_stock.quantity >= quantity):
				user_stock.quantity = user_stock.quantity - quantity
				user_stock.save()
				if user_stock.quantity == 0:
					user_stock.delete()

				user.balance = user.balance + (quantity * bid_price)
				user.save()
			else:
				return (False, "You do not own that many stocks to sell.")
				
        return (True, "Order placed successfully.")


# == Application View Functions ===
@login_required
def exchange(request, symbol):
	flash_message = None
	company_name = None
	bid_price = None
	ask_price = None
	valid_symbol = False
	
	data = get_symbol(symbol)
	if data:
		company_name = data['name']
		bid_price = float(data['bid'])
		ask_price = float(data['ask'])
		valid_symbol = True

	if request.method == 'POST':
		form = OrderForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			(success, flash_message) = place_order(
            	request,
                cd['symbol'],
                cd['order_type'],
                int(cd['quantity']),
            )
			if success:
				return HttpResponseRedirect(reverse('exchange', args=(symbol,)))			
	else:
		form = OrderForm(
			initial={'symbol': symbol}
		)
	
	# get portfolio values after any orders placed
	stock_list = None
	if request.user.is_authenticated():
		stock_list = Holdings.objects.filter(owner=request.user)

	return render(request, 'portfolio/exchange.html', {'symbol': symbol, 'company_name': company_name, 'bid_price': bid_price, 'ask_price': ask_price,
							'stock_list': stock_list, 'form': form, 'flash_message': flash_message, 'valid_symbol': valid_symbol })

benzinga-exchange/portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <!-- Bootstrap core CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<link rel="stylesheet" href="//code.jquery.com/ui/1.11.1/themes/smoothness/jquery-ui.css">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="/static/style.css" />
    <title>{% block title %}Steve's Simple Stock Exchange{% endblock %}</title>
</head>

<body>


    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Steve's Simple Stock Exchange</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          	<li class="dropdown">
			   <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello {{ user }} <span class="caret"></span></a>
				<ul class="dropdown-menu" role="menu">
				<li><a href="/portfolio/">Portfolio</a></li>
				<li><a href="/accounts/logout/">Logout</a></li>
			  </ul>
            </li>
            {% else %}
            <a href="/accounts/login" role="button" class="btn btn-success btn-large">Login</a>
            <a href="/accounts/login" role="button" class="btn btn-success btn-large">Create Account</a>
            {% endif %}
          </ul>
          <form class="navbar-form navbar-left" role="form">
            <i class="fa fa-search"></i>
            <div class="form-group has-feedback">
          	       <i class="glyphicon glyphicon-search form-control-feedback"></i>                
                   <input type="text" placeholder="Enter Symbol" class="form-control" id="txtTicker">
            </div>
            <button id="lookup" type="submit" class="btn btn-success">Lookup</button>
          </form>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container-fluid">
    <div class="jumbotron">
    
    {% if flash_message %}
    <p class="error" style="color: red;">{{ flash_message }}</p>
    {% endif %}
    
      <div class="row">
           <div class="col-md-6">
                {% block content %}{% endblock %}
		   </div>
		   <div class="col-md-5 col-md-offset-1">
               {% block rightside %}{% endblock %}
           </div>
        </div>
    </div>
    </div><!-- /.container -->

    <div class="footer">
      <div class="container-fluid">
        <p class="text-muted">&copy; Copyright Steve Rawlinson 2014.</p>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//code.jquery.com/ui/1.11.1/jquery-ui.js"></script>
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	
	<script src="/static/custom.js"></script>
	
	
</body>
</html>

benzinga-exchange/portfolio/templates/portfolio/exchange.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Steve's Simple Stock Exchange{% endblock %}

{% block content %}

<div class="row">

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

{% if valid_symbol %}
   <h2>{{company_name}} ({{ symbol|upper }})</h2>
	<div class="row">
		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading"><b>Buy {{company_name}} ({{ symbol|upper }})</b></div>
				<div class="panel-body">
				    <form action="" method="post">
						<p>Ask Price: ${{ ask_price |floatformat:"2" }}</p>
						<input id="id_symbol" name="symbol" type="hidden" value="{{ symbol }}" />
						<p><label for="id_quantity">Quantity:</label> <input id="id_quantity" name="quantity" type="number" />{{ form.quantity.errors }}</p>
						<input id="id_order_type" name="order_type" type="hidden" value="buy" />
					
        {% csrf_token %}
        <input type="submit" value=" Buy " class="btn btn-success">
					</form>
				</div>
			</div>	
		</div>
		<div class="col-md-6">
			<div class="panel panel-primary">
				<div class="panel-heading"><b>Sell {{company_name}} ({{ symbol | upper}})</b></div>
				<div class="panel-body">
				    <form action="" method="post">
						<p>Bid Price: ${{ bid_price |floatformat:"2" }}</p>
						<input id="id_symbol" name="symbol" type="hidden" value="{{ symbol }}" />
						<p><label for="id_quantity">Quantity:</label> <input id="id_quantity" name="quantity" type="number" />{{ form.quantity.errors }}</p>
						<input id="id_order_type" name="order_type" type="hidden" value="sell" />
						{% csrf_token %}
						<input type="submit" value=" Sell " class="btn btn-success">
					</form>
				</div>
			</div>	
		</div>
	</div>
</div>


<div class="row" style="height:600px;">
<h2>Real-time Chart and News</h2>
<!-- TradingView Widget BEGIN -->
<script type="text/javascript" src="https://d33t3vvu2t2yu5.cloudfront.net/tv.js"></script>
<script type="text/javascript">
new TradingView.widget({
  "autosize": true,
  "symbol": "{{ symbol }}",
  "interval": "D",
  "timezone": "exchange",
  "theme": "White",
  "style": "1",
  "toolbar_bg": "#f1f3f6",
  "details": true,
  "news": [
    "stocktwits",
    "headlines"
  ],
  "hideideas": true,
  "show_popup_button": true,
  "popup_width": "1000",
  "popup_height": "650"
});
</script>
<!-- TradingView Widget END -->
</div>

{% else %}
	{% if symbol %}
    <p>Sorry, the symbol {{ symbol }} was not found.
    {% else %}
    <p>Missing symbol.
    {% endif %}
    
    <br/>Use the <b>Lookup</b> above to find a stock.</p>
{% endif %}



{% endblock %}


{% block rightside %}
		<div class="row">
			<div class="col-md-6">
        		<h2>Current Portfolio</h2>
        	</div>
        	<div class="col-md-6">
        		<h2>Cash: 
        		{{ user.userprofile.balance|floatformat:"2" }}</h2>
        	</div>
        </div>
        
		<div class="row">
			<div class="panel panel-default">
		
			{% if stock_list %}
				<!-- Table -->
				<table class="table">
					<thead>
						<tr>
						<th>Company</th>
						<th>Quantity</th>
						<th>Price Paid</th>
						<th>Book Value</th>
						<th></th>
					</thead>
					<tbody>
					{% for stock in stock_list %}
					<tr>
						<td>{{ stock.company_name }}</td>
						<td>{{ stock.quantity|floatformat:"0" }}</td>
						<td>${{ stock.price_paid|floatformat:"2" }}</td>
						<td>${% widthratio stock.price_paid 1 stock.quantity %}</td>
						<td><a class="btn btn-default" href="{% url 'exchange' stock.symbol %} " role="button">View Stock &raquo;</a></td>
					</tr>
					{% endfor %}
					</tbody>
				</table>
			{% else %}
				<p>Sorry, no stocks in your portfolio.</p>
				<p>Use <b>Lookup</b> to find a stock and then <b>buy</b> it.</p>
				<p>Here are some suggestions: <a href="/portfolio/f/">Ford</a> and <a href="/portfolio/goog/">Google</a>.
			{% endif %}
				
			</div>
		</div>

{% endblock %}